import Head from 'next/head'
import SignIn from '../components/users/SignIn'

export default function Home() {
  return (
    <>
      <Head>
        <title>Event Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Event Planner</h1>

      <SignIn />
    </>
  )
}
